# Travis-CI script for the Self-adaptation manager
#
# This is being developed for the TANGO Project: http://tango-project.eu
#
# Copyright: Richard Kavanagh, University of Leeds, 2016.
#
# This code is licensed under an Apache 2.0 license. Please, refer to the LICENSE.TXT file for more information

language: java
jdk:
  - oraclejdk8
  
# SonnarQube Configuration
addons:
  sonarcloud: true

script: mvn install -DskipTest -q
  
- sonar-scanner -X -Dsonar.login="4bfd776407ac9a01b64454c66f5dcb811a7acc49"